name: CI

on:
  push:
    tags-ignore: * # Don't build when a tag is created
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: DbUp/Universe/.github/workflows/build.yml@reusable
