name: Test Report
run-name: Generate Test Report for workflow ${{ github.event.workflow_run.name }} run ${{ github.event.workflow_run.run_number }} branch ${{ github.event.workflow_run.head_branch }}

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  report:
    name: Test Report 🧪
    uses: DbUp/Universe/.github/workflows/ReusableWorkflows/test-report.yml@main